config/routes.rb
Rails.application.routes.draw do

  root to: 'users#index'

  resources :users, only: [:show, :index, :edit, :update, :new, :create]

  resources :messages, only: [:create]

  get 'login', to: 'session#new', as: 'login'
  post 'login', to: 'session#create'
  get 'logout', to: 'session#destroy', as: 'logout'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :messages, dependent: :destroy
  validates :name, :email, :password, :password_confirmation, presence: true
  validates :name, :email, :password, length: { in: 3..20 }
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def signed_in?
    !current_user.nil?
  end

  def require_login
    redirect_to login_path, notice: 'nem' unless signed_in?
  end

  def require_correct_user
    redirect_to root_path, notice: 'nem, nem' unless signed_in? && (@current_user == @user)
  end

  def sign_in(user)
    session[:user_id] = user.id
  end

  def sign_out
    session[:user_id] = nil
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @message = current_user.messages.create(message_params)
    redirect_to root_path, notice: 'message sent'
  end

private

  def message_params
    params.require(:message).permit(:text)
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by_email(params[:email])

    if @user && @user.authenticate(params[:password])
      sign_in(@user)
      redirect_to root_path, notice: 'logged in'
    else
      render :new
    end

  end

  def destroy
    sign_out
    redirect_back fallback_location: root_path, notice: 'logged out'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  before_action :find_user, only: [:show, :edit, :update]
  before_filter :require_correct_user, only: [:edit, :update]

  def index
    @users = User.all
    @message = current_user.messages.build if signed_in?
    @messages = Message.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to login_path, notice: 'user created'
    else
      render :new
    end

  end

  def show
  end

  def edit
  end

  def update
    if @user.save
      redirect_to @user, notice: 'stuff changed'
    else
      render :edit
    end
  end

private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :available)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<div class='left'>
  <h1><%= link_to 'vagy ma?', root_path %></h1>
</div>

<div class='right'>
  <% if signed_in? %>
    <%= image_tag 'fasz.png' %>
    <%= link_to "#{current_user.name}", edit_user_path(current_user) %>
    <%= link_to 'logout', logout_path %>
  <% else %>
    <%= link_to 'registration', new_user_path %>
    <%= link_to 'login', login_path %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>vagy ma?</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>

    <% if notice %>
      <div class='notice'><%= notice %></div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for @message do |f| %>

  <%= f.text_field :text %>

  <%= f.submit 'send' %>

<% end %>

app/views/session/_form.html.erb
<%= form_tag login_path do %>
  <%= label_tag :email %>
  <%= text_field_tag :email %>

  <%= label_tag :password %>
  <%= password_field_tag :password %>

  <%= submit_tag 'go' %>
<% end %>

app/views/session/new.html.erb
<section><%= render 'form' %></section>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div class="error">
    <% @user.errors.full_messages.each do |m| %>
        <p><%= m %></p>
    <% end %>
  </div>
<% end %>

<%= form_for @user do |f| %>
  <%= f.label :name, 'Name:' %>
  <%= f.text_field :name %>

  <%= f.label :email, 'E-mail:' %>
  <%= f.text_field :email %>

  <%= f.label :password, 'Password:' %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, 'Password Confirmation' %>
  <%= f.password_field :password_confirmation %>

  <%= f.label :available, 'Available?' %>
  <%= f.check_box :available %>

  <%= f.submit 'Send' %>
<% end %>

app/views/users/_messages.html.erb
<% @messages.each do |m| %>
  <article>
    <h3><%= m.user.name %> - <%= m.created_at %></h3>
    <p><%= m.text %></p>
  </article>
<% end %>

app/views/users/_time.html.erb
<%= Time.now %>

app/views/users/_userlist.html.erb
<table>
  <tbody>
    <% @users.each do |u| %>
      <tr>
        <td>
          <strong>
            <%= u.name %>
          </strong>
        </td>
        <td>
          <% if u.available %>
            <p>leszek</p>
          <% else %>
            <p>nem leszek</p>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/edit.html.erb
<section><%= render 'form' %></section>

app/views/users/index.html.erb
<section class='time center'><%= render 'time' %></section>
<section class='userlist'><%= render 'userlist' %></section>
<section class='messages'><%= render 'messages' %></section>

<% if signed_in? %>
  <footer>
    <%= render 'messages/form' %>
  </footer>
<% end %>

app/views/users/new.html.erb
<section><%= render 'form' %></section>

app/views/users/show.html.erb
<%= @user.name %>
<% if current_user == @user %>
  <%= link_to 'edit', edit_user_path(current_user) %>
<% end %>